/*
 * A singleton class to hold random number generators for use in Boolean gene networks.
 */

#pragma once

#include <array>
#include <morph/Random.h>
#include <morph/bn/Genosect.h>

namespace morph {
    namespace  bn {

        //! Access random number generators for boolean gene networks
        template<size_t N=5, size_t K=5>
        class Random
        {
            using genosect_t = typename Genosect<K>::type;

            //! Private constructor/destructor
            Random() {};
            ~Random() {};
            //! A pointer returned to the single instance of this class
            static Random* pInstance;

        public:
            //! The instance public function. Uses the very short name 'i' to keep code tidy.
            static Random* i()
            {
                // <N,K> template args seem to be optional here, at least on g++/icpc
                if (Random::pInstance == 0) {
                    Random::pInstance = new morph::bn::Random;
                    //Random::i()->init(); // If required
                }
                return Random::pInstance;
            }

            //! Hold an array to place random numbers in of 'genosect_t width' - gw
            static constexpr size_t gw = N*(1<<K);
            //! An array to hold a sequence of random floats generated by frng
            std::array<float, gw> rnums;

            //! Populate rnums with gw new random numbers.
            //! See https://www.aerialmantis.co.uk/blog/2017/03/17/template-keywords/ to
            //! explain the odd looking .template get<> syntax.
            void fill_rnums() { this->frng.template get<gw> (rnums); }

            //! A random number generator of width genosect_t.
            morph::RandUniform<genosect_t, std::mt19937> genosect_rng;

            //! A floating point random number generator
            morph::RandUniform<float, std::mt19937> frng;
        };
    }
}
