% Short script to plot curve and control points generated by testbez.cpp.
c = csvread ('curve.csv');
ctrl = csvread('ctrl.csv');

figure(33); clf;
hold off;
plot (c(:,2),c(:,3),'b-')
hold on;
plot (ctrl(1:2,1),ctrl(1:2,2),'ro-')
plot (ctrl(3:4,1),ctrl(3:4,2),'ro-')
