name: Windows 2022
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
      - 'examples/screenshots/**'
      - 'examples/docs/**'
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: rremilian/morphologica/.github/workflows/cmake-windows-template.yml@fix/vcpkg_baseline
    with:
      RUNNER_IMAGE: windows-2022
      BUILD_TYPE: Release
      VCPKG_TRIPLET: x64-windows