name: Ubu24 gladmx
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: ABRG-Models/morphologica/.github/workflows/cmake-ubuntu-template.yml@359-windows-gl-headers
    with:
      RUNNER_IMAGE: ubuntu-24.04
      BUILD_TYPE: Release
      CC: gcc-13
      CXX: g++-13
      GLAD_MX: ON
