on:
  workflow_call:
    inputs:
      CONTAINER_IMAGE:
        required: true
        type: string
      BUILD_TYPE:
        required: true
        type: string
      CC:
        required: true
        type: string
      CXX:
        required: true
        type: string

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ input.CONTAINER_IMAGE }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        brew update
        brew install gh

    - name: Install dependencies
      run: |
        brew update
        brew install libomp glfw armadillo hdf5 nlohmann-json

    - name: Install dependencies (MacOS 13)
      run: |
        #brew unlink python@3.12 && brew link --overwrite python@3.12 # Hack to prevent brew-installed python from interfering with preinstalled python
        # maybe: brew unlink python && brew link --overwrite python # alt hack
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete # Alt hack
        brew update
        brew install libomp glfw armadillo hdf5 nlohmann-json
      if: ${{ inputs.CONTAINER_IMAGE == "macos-13" }}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ input.BUILD_TYPE }} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{ input.BUILD_TYPE }}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{ input.BUILD_TYPE }}
