name: Mac OS 14
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: rremilian/morphologica/.github/workflows/cmake-mac-template.yml@feat/github_actions_improvments
    with:
      CONTAINER_IMAGE: macos-14
      BUILD_TYPE: Release
      CC: clang-15
      CXX: clang++-15