name: Ubuntu latest
on:
#  push:
#    branches: [ "main" ]
#    paths-ignore:
#      - 'docs/**'
#      - 'README**'
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  call-workflow-passing-data:
    uses: ABRG-Models/morphologica/.github/workflows/cmake-ubuntu-template.yml@main
    with:
      RUNNER_IMAGE: ubuntu-latest
      BUILD_TYPE: Release
      CC: gcc
      CXX: g++
