name: Ubuntu 22.04
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: rremilian/morphologica/.github/workflows/cmake-ubuntu-template.yml@main
    with:
      CONTAINER_IMAGE: ubuntu-22.04
      BUILD_TYPE: Release
      CC: gcc-13
      CXX: g++-13
