name: Ubu 24 clang17
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
      - 'examples/screenshots/**'
      - 'examples/docs/**'
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-passing-data:
    uses: ABRG-Models/morphologica/.github/workflows/cmake-ubuntu-template.yml@main
    with:
      RUNNER_IMAGE: ubuntu-24.04
      BUILD_TYPE: Release
      CC: clang-17
      CXX: clang++-17
      WX_PACKAGE: libwxgtk3.2-dev
