name: Ubu 24 clang17
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: rremilian/morphologica/.github/workflows/cmake-ubuntu-template.yml@github_actions_improvments
    with:
      CONTAINER_IMAGE: ubuntu-24.04
      BUILD_TYPE: Release
      CC: clang-17
      CXX: clang++-17